// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5459.BlackbirdRobotBuilder;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainSpeedControllerRight;
    public static SpeedController driveTrainSpeedControllerLeft;
    public static RobotDrive driveTrainRobotDrive21;
    public static SpeedController climberclimberMotor;
    public static DoubleSolenoid bucketbucketSolenoid;
    public static Solenoid shiftersrightShifter;
    public static Solenoid shiftersleftShifter;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainSpeedControllerRight = new Talon(1);
        LiveWindow.addActuator("DriveTrain", "SpeedControllerRight", (Talon) driveTrainSpeedControllerRight);
        
        driveTrainSpeedControllerLeft = new Talon(2);
        LiveWindow.addActuator("DriveTrain", "SpeedControllerLeft", (Talon) driveTrainSpeedControllerLeft);
        
        driveTrainRobotDrive21 = new RobotDrive(driveTrainSpeedControllerLeft, driveTrainSpeedControllerRight);
        
        driveTrainRobotDrive21.setSafetyEnabled(true);
        driveTrainRobotDrive21.setExpiration(0.1);
        driveTrainRobotDrive21.setSensitivity(0.5);
        driveTrainRobotDrive21.setMaxOutput(1.0);

        climberclimberMotor = new Talon(0);
        LiveWindow.addActuator("Climber", "climberMotor", (Talon) climberclimberMotor);
        
        bucketbucketSolenoid = new DoubleSolenoid(0, 0, 1);
        LiveWindow.addActuator("Bucket", "bucketSolenoid", bucketbucketSolenoid);
        
        shiftersrightShifter = new Solenoid(0, 2);
        LiveWindow.addActuator("Shifters", "rightShifter", shiftersrightShifter);
        
        shiftersleftShifter = new Solenoid(0, 3);
        LiveWindow.addActuator("Shifters", "leftShifter", shiftersleftShifter);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
